作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [3]:
import numpy as np

In [4]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [5]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
array1.reshape((5,6), order= "F")

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [7]:
#2.呈上題的array，找出被6除餘1的數的索引
np.where(array1/6 == i) #可運用np.where找出索引

NameError: name 'i' is not defined

In [8]:
#remainder可以找出餘數
np.remainder(array1, 6)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3,
       4, 5, 0, 1, 2, 3, 4, 5], dtype=int32)

In [9]:
#組合where+remainder
np.where(np.remainder(array1, 6) == 1)

(array([ 1,  7, 13, 19, 25], dtype=int64),)

In [10]:
####要使用reshape後的array回答
####調整如下

In [12]:
#1
a= array1.reshape((5,6), order='F')
a

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [13]:
#2
np.where(np.remainder(a, 6) == 1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))

In [14]:
#解答的做法
## 算術運算符為：+, -, *, / , %, // , **, _ 分別為加、減、乘、浮點除、取餘數、整數除、冪運算、上個表達式結果的值。

np.where(a%6==1)

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))